<% for size in ['XS', 'S', 'M', 'L', 'XL']%>
<%= size %>:
  name: <%= size %>
  presentation: <%= size %>
  position: 1
  option_type: taglie_generiche
<% end %>

<% for size in ['8', '10', '12', '14', '16']%>
<%= size %>_oz:
  name: <%= size %> oz
  presentation: <%= size %> oz
  position: 1
  option_type: taglie_guantoni
<% end %>

<% for size in 36..47 %>
<%= size %>:
  name: <%= size %>
  presentation: <%= size %>
  position: 1
  option_type: taglie_scarpe
<% end %>